apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  airflow.cfg: |
    [logging]
    remote_logging = False
    logging_level = INFO
    [core]
    load_examples = False
    executor = KubernetesExecutor
    dags_folder = /opt/airflow/dags
    
    # ДОБАВЬ ЭТИ СТРОКИ СЮДА:
    [kubernetes_env_vars]
    USER = airflow
    AIRFLOW_USER_NAME = airflow
