apiVersion: v1
kind: Pod
metadata:
  name: placeholder
spec:
  securityContext:
    fsGroup: 0
    runAsUser: 1000
  containers:
    - name: base
      image: cr.yandex/crpu8nteef4qpg86ffj6/airflow-spark:22
      env:
        - name: USER
          value: "airflow"
        - name: AIRFLOW_USER_NAME
          value: "airflow"
      volumeMounts:
        - name: config
          mountPath: /opt/airflow/airflow.cfg
          subPath: airflow.cfg
  volumes:
    - name: config
      configMap:
        name: airflow-config
